#!/usr/bin/env python3
"""Per-frame spectrum of an audio file, for music-driven visuals.

Writes one row of band energies (0-1) per video frame:

    {"fps": 30, "bands": 48, "duration": 52.0, "frames": [[...48 floats...], ...]}

Bands are mel-spaced (bass at index 0), log-compressed, and normalized
against the loudest band over the whole track, so quiet passages stay quiet.
Deterministic: the same file always gives the same JSON.

    python3 scripts/spectrum.py audio/track.opus -o spectrum.json --fps 30 --bands 48
"""

import argparse
import json
import sys

import librosa
import numpy as np


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("audio")
    parser.add_argument("-o", "--out", required=True)
    parser.add_argument("--fps", type=int, default=30)
    parser.add_argument("--bands", type=int, default=48)
    parser.add_argument("--js-global", help="write `window.<NAME> = {...};` instead of plain JSON")
    args = parser.parse_args()

    sr = 44100
    y, _ = librosa.load(args.audio, sr=sr, mono=True)
    hop = sr // args.fps
    mel = librosa.feature.melspectrogram(
        y=y, sr=sr, n_fft=4096, hop_length=hop, n_mels=args.bands, fmin=30, fmax=14000, power=2.0
    )
    db = librosa.power_to_db(mel, ref=np.max)  # 0 dB = loudest bin in the track
    floor = -60.0
    norm = np.clip((db - floor) / -floor, 0.0, 1.0)

    # Light temporal smoothing so single-frame spikes don't jitter.
    kernel = np.array([0.25, 0.5, 0.25])
    norm = np.apply_along_axis(lambda row: np.convolve(row, kernel, mode="same"), 1, norm)

    frames = [[round(float(v), 3) for v in column] for column in norm.T]
    payload = {"fps": args.fps, "bands": args.bands, "duration": round(len(y) / sr, 3), "frames": frames}

    with open(args.out, "w") as f:
        if args.js_global:
            f.write(f"// Generated by scripts/spectrum.py from {args.audio}\n")
            f.write(f"window.{args.js_global} = {json.dumps(payload, separators=(',', ':'))};\n")
        else:
            json.dump(payload, f, separators=(",", ":"))
    print(f"spectrum: {len(frames)} frames x {args.bands} bands -> {args.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
